project_id = "betfolio"

[auth]
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.claim-username]
verify_jwt = true

[functions.process-betslip]
verify_jwt = true

[functions.finalize-bet-import]
verify_jwt = true
