"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronRight, Search, SlidersHorizontal } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Input, Select } from "@/components/ui/field";
import type { BetListItem } from "@/lib/bets";
import { formatMoney, titleCase } from "@/lib/utils";

export function BetsTable({ bets }: { bets: BetListItem[] }) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [type, setType] = useState("all"); const [currency, setCurrency] = useState("all");
  const filtered = useMemo(() => bets.filter((bet) => (!search || `${bet.bookmaker} ${bet.externalBetId}`.toLowerCase().includes(search.toLowerCase())) && (status === "all" || bet.status === status) && (type === "all" || bet.betType === type) && (currency === "all" || bet.currency === currency)), [bets, search, status, type, currency]);
  return <><Card className="mt-7 p-3"><div className="grid gap-2 md:grid-cols-[1fr_repeat(3,150px)]"><div className="relative"><Search className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-zinc-600" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search bookmaker or Bet ID" className="pl-10" /></div><Select aria-label="Status filter" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option>{["won", "lost", "void", "cashout"].map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</Select><Select aria-label="Bet type filter" value={type} onChange={(e) => setType(e.target.value)}><option value="all">All bet types</option>{["single", "accumulator", "bet_builder"].map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</Select><Select aria-label="Currency filter" value={currency} onChange={(e) => setCurrency(e.target.value)}><option value="all">All currencies</option>{[...new Set(bets.map((bet) => bet.currency))].map((item) => <option key={item}>{item}</option>)}</Select></div></Card>
    <Card className="mt-4 overflow-hidden"><div className="hidden grid-cols-[1.2fr_1fr_.7fr_.7fr_.7fr_.7fr_.8fr_40px] gap-3 border-b border-white/[.07] px-5 py-3 text-[10px] font-bold uppercase tracking-[.11em] text-zinc-600 md:grid"><span>Bookmaker</span><span>Bet</span><span>Stake</span><span>Odds</span><span>Status</span><span>P&amp;L</span><span>Settled</span><span /></div>{filtered.length ? <div className="divide-y divide-white/[.06]">{filtered.map((bet) => <Link key={bet.id} href={`/bets/${bet.id}`} className="grid grid-cols-[1fr_auto] items-center gap-3 px-5 py-4 transition hover:bg-white/[.025] md:grid-cols-[1.2fr_1fr_.7fr_.7fr_.7fr_.7fr_.8fr_40px]"><div><p className="text-sm font-semibold">{bet.bookmaker}</p><p className="mt-1 text-[11px] text-zinc-600">{bet.externalBetId ?? "No Bet ID"}</p></div><span className="hidden text-xs text-zinc-400 md:block">{titleCase(bet.betType)}</span><span className="hidden text-xs text-zinc-400 md:block">{formatMoney(bet.cashStake, bet.currency)}</span><span className="hidden text-xs text-zinc-400 md:block">{bet.odds?.toFixed(2) ?? "—"}</span><span className="hidden text-xs md:block"><span className={`rounded-full px-2 py-1 ${bet.status === "won" ? "bg-lime-300/10 text-lime-300" : bet.status === "lost" ? "bg-red-300/10 text-red-300" : "bg-white/[.05] text-zinc-400"}`}>{titleCase(bet.status)}</span></span><span className={`text-sm font-semibold md:text-xs ${bet.pnl > 0 ? "text-lime-300" : bet.pnl < 0 ? "text-red-300" : "text-zinc-400"}`}>{formatMoney(bet.pnl, bet.currency, true)}</span><span className="hidden text-xs text-zinc-500 md:block">{bet.settledAt ? new Date(bet.settledAt).toLocaleDateString() : "—"}</span><ChevronRight className="hidden size-4 text-zinc-700 md:block" /><div className="col-span-2 flex gap-2 text-[11px] text-zinc-600 md:hidden"><span>{titleCase(bet.betType)}</span><span>·</span><span>{formatMoney(bet.cashStake, bet.currency)}</span><span>·</span><span>{titleCase(bet.status)}</span></div></Link>)}</div> : <div className="px-5 py-20 text-center"><SlidersHorizontal className="mx-auto size-6 text-zinc-700" /><p className="mt-4 font-semibold">No bets match these filters.</p><p className="mt-2 text-sm text-zinc-600">Try widening your search.</p></div>}</Card></>;
}
