import type { BetslipExtraction } from "./schema";

export const mockExtractions: Record<string, BetslipExtraction> = {
  winning_accumulator: {
    documentType: "settled_betslip", bookmaker: { name: "Bet365" }, externalBetId: "O/9482612/0001876", betType: "accumulator", status: "won", currency: "GBP",
    cashStake: 20, promotionalStake: 0, displayedReturn: 94.4, returnKind: "gross_return", totalOddsRaw: "4.72", totalOddsDecimal: 4.72, oddsFormat: "decimal", placedAt: "2026-08-20T15:18:00Z", settledAt: "2026-08-20T20:42:00Z",
    legs: [
      { position: 1, sport: "Football", competition: "Premier League", eventName: "Arsenal v Everton", market: "Match Result", selection: "Arsenal", oddsRaw: "1.65", oddsDecimal: 1.65, result: "won" },
      { position: 2, sport: "Football", competition: "Premier League", eventName: "Liverpool v Brighton", market: "Total Goals", selection: "Over 2.5", oddsRaw: "2.86", oddsDecimal: 2.86, result: "won" },
    ], evidence: { stakeText: "Stake £20.00", returnText: "Returns £94.40", statusText: "Won", betIdText: "Bet ID O/9482612/0001876" },
  },
  losing_single: { documentType: "settled_betslip", bookmaker: { name: "Sky Bet" }, externalBetId: "SB-813842", betType: "single", status: "lost", currency: "GBP", cashStake: 35, promotionalStake: 0, displayedReturn: 0, returnKind: "gross_return", totalOddsRaw: "2.10", totalOddsDecimal: 2.1, oddsFormat: "decimal", placedAt: null, settledAt: null, legs: [{ position: 1, sport: "Football", competition: null, eventName: "Chelsea v Fulham", market: "Match Result", selection: "Chelsea", oddsRaw: "2.10", oddsDecimal: 2.1, result: "lost" }], evidence: { stakeText: "£35.00", returnText: "£0.00", statusText: "Lost", betIdText: "SB-813842" } },
  winning_single: { documentType: "settled_betslip", bookmaker: { name: "William Hill" }, externalBetId: "WH-30322", betType: "single", status: "won", currency: "GBP", cashStake: 10, promotionalStake: 0, displayedReturn: 26, returnKind: "gross_return", totalOddsRaw: "2.60", totalOddsDecimal: 2.6, oddsFormat: "decimal", placedAt: null, settledAt: null, legs: [], evidence: { stakeText: "£10", returnText: "Return £26", statusText: "Won", betIdText: "WH-30322" } },
  void: { documentType: "settled_betslip", bookmaker: { name: "Paddy Power" }, externalBetId: "PP-VOID-1", betType: "single", status: "void", currency: "GBP", cashStake: 20, promotionalStake: 0, displayedReturn: 20, returnKind: "refund", totalOddsRaw: null, totalOddsDecimal: null, oddsFormat: null, placedAt: null, settledAt: null, legs: [], evidence: { stakeText: "£20", returnText: "Refund £20", statusText: "Void", betIdText: "PP-VOID-1" } },
  cashout: { documentType: "settled_betslip", bookmaker: { name: "Betfair" }, externalBetId: "BF-CASH-1", betType: "single", status: "cashout", currency: "GBP", cashStake: 20, promotionalStake: 0, displayedReturn: 27.5, returnKind: "cashout", totalOddsRaw: null, totalOddsDecimal: null, oddsFormat: null, placedAt: null, settledAt: null, legs: [], evidence: { stakeText: "£20", returnText: "Cashed out £27.50", statusText: "Cashed out", betIdText: "BF-CASH-1" } },
  ambiguous: { documentType: "settled_betslip", bookmaker: { name: null }, externalBetId: null, betType: null, status: "partial_cashout", currency: null, cashStake: null, promotionalStake: 0, displayedReturn: 18, returnKind: "unknown", totalOddsRaw: null, totalOddsDecimal: null, oddsFormat: null, placedAt: null, settledAt: null, legs: [], evidence: { stakeText: null, returnText: "Winnings 18", statusText: "Partial cash out", betIdText: null } },
};
